In [1]:
import numpy as np

In [2]:
a = [1,3,2,5]
#Assigning array to numpy
arr1 = np.array(a)

In [3]:
arr1

array([1, 3, 2, 5])

In [4]:
b = [3,5,6,7]

In [5]:
# two Dimentional Array
arr2D = np.array([a,b])
arr2D

array([[1, 3, 2, 5],
       [3, 5, 6, 7]])

In [6]:
arr2D.shape

(2, 4)

In [7]:
#arange method
A = np.arange(10)

In [8]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
#arange with start, stop and coondition
B = np.arange(5,80,3)

In [10]:
B

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50, 53,
       56, 59, 62, 65, 68, 71, 74, 77])

In [11]:
#Reshape with arange
C = np.arange(25).reshape(5,5)

In [12]:
C

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [13]:
#Shape method
C.shape

(5, 5)

In [16]:
#Sum method
C.sum()

300

In [17]:
# numpy zeros method
x = np.zeros(10)

In [18]:
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
# data type finding in numpy using dtype
x.dtype

dtype('float64')

In [24]:
# numpy ones method 
z = np.ones([1,1])

In [22]:
z

array([[[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]])

# # Arithmetic Arrays

In [28]:
arr = np.array([[1,2,3,4],[5,6,7,8]])

In [29]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [30]:
#Adding value to array
arr+18

array([[19, 20, 21, 22],
       [23, 24, 25, 26]])

In [31]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [34]:
#squering the array
arr * arr

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [33]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [35]:
#power of array
arr **2

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]], dtype=int32)

In [37]:
arr ** 3

array([[  1,   8,  27,  64],
       [125, 216, 343, 512]], dtype=int32)

In [38]:
arr -arr

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [39]:
# transpose array
A = np.arange(25).reshape(5,5)

In [40]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [41]:
A.T

array([[ 0,  5, 10, 15, 20],
       [ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24]])

In [42]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [43]:
B = np.arange(6).reshape(2,3)

In [44]:
B

array([[0, 1, 2],
       [3, 4, 5]])

In [45]:
B.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [46]:
bt = B.T

In [48]:
# dot product between ararys
np.dot(B,bt)

array([[ 5, 14],
       [14, 50]])

# # # Arrays Slices are views 

In [51]:
A = np.arange(20)

In [52]:
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [53]:
a1 = A[:10]

In [54]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
#Slicices of ararys get modify in the numpy
a1[:] = 100

In [56]:
a1

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [57]:
A

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [58]:
x = list(range(20))

In [59]:
x

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [60]:
y = x[:10]

In [61]:
y

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [63]:
y[0] = 20

In [64]:
y

[20, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [65]:
x

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [66]:
A = np.arange(20)

In [67]:
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [68]:
b = A.copy()

In [69]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [70]:
b [0] = 100

In [71]:
b

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [72]:
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [73]:
A = np.arange(25).reshape(5,5)

In [74]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [75]:
A[0]

array([0, 1, 2, 3, 4])

In [76]:
A[1][3]

8

In [78]:
A[1][4]

9

In [80]:
A[2:4,1:4]

array([[11, 12, 13],
       [16, 17, 18]])

In [81]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [83]:
A[[1,4,4]]

array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24],
       [20, 21, 22, 23, 24]])

In [85]:
A.sum()


300

In [86]:
A[[1,3,4]].sum()

230